{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "talos-fleet-controller.serviceAccountName" . }}
  namespace: {{ include "talos-fleet-controller.namespace" . }}
  labels:
    {{- include "talos-fleet-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
