---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
- apiGroups:
  - fleet.talos.dev
  resources:
  - fleetnodesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fleet.talos.dev
  resources:
  - fleetnodesets/finalizers
  verbs:
  - update
- apiGroups:
  - fleet.talos.dev
  resources:
  - fleetnodesets/status
  verbs:
  - get
  - patch
  - update
