apiVersion: v1
kind: Namespace
metadata:
  name: tfc-system
  labels:
    app.kubernetes.io/name: talos-fleet-controller
    # Privileged PSS — controller needs Node access
    pod-security.kubernetes.io/enforce: privileged
